1. Create a class Employee and then do the following
• Create a data member to count the number of Employees
• Create a constructor to initialize name, family, salary, department
• Create a function to average salary
• Create a Fulltime Employee class and it should inherit the properties of Employee class
• Create the instances of Fulltime Employee class and Employee class and call their member functions.

In [6]:
class Employee:
    employee_count = 0  # Data member to count the number of Employees

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.employee_count += 1

    def average_salary(self, total_salary):
        return total_salary / Employee.employee_count

class FulltimeEmployee(Employee):
    # Inheriting properties from the Employee class
    pass

# Creating instances of Employee class
employee1 = Employee("Yashwanth", "Polneni", 200000, "HR")
employee2 = Employee("Vijay", "Bhaskar", 80000, "IT")

# Creating instances of FulltimeEmployee class
fulltime_employee1 = FulltimeEmployee("Lucky", "Reddy", 70000, "Finance")
fulltime_employee2 = FulltimeEmployee("Loki", "Lokesh", 60000, "Marketing")

# Calling member functions
total_salary_employees = employee1.salary + employee2.salary
average_salary_employees = employee1.average_salary(total_salary_employees)

total_salary_fulltime_employees = fulltime_employee1.salary + fulltime_employee2.salary
average_salary_fulltime_employees = fulltime_employee1.average_salary(total_salary_fulltime_employees)

# Displaying results
print("Average Salary for Employees:", average_salary_employees)
print("Average Salary for Fulltime Employees:", average_salary_fulltime_employees)

Average Salary for Employees: 70000.0
Average Salary for Fulltime Employees: 32500.0


2. Numpy
Using NumPy create random vector of size 20 having only float in the range 1-20.
Then reshape the array to 4 by 5
Then replace the max in each row by 0 (axis=1)
(you can NOT implement it via for loop)

In [7]:
# Import the NumPy library and alias it as 'np' for brevity and convention.
import numpy as np

# Create a random vector of size 20 with floats in the range 1-20
random_vector = np.random.uniform(1, 20, 20)

print("Original Random Vector:\n", random_vector)

Original Random Vector:
 [17.80415106  9.52765923  2.88787368 14.37015557 15.49952502 16.94020624
 16.58653919  8.64956199  5.22977406 15.07709748 12.77279528  7.13744974
 16.98808919  9.75738691 18.39519337 12.05685587 12.41582629  9.17755999
 13.847821   16.75668494]


In [8]:
# Reshape the array to 4 by 5 (4 rows and 5 columns)
reshaped_array = random_vector.reshape(4, 5)

print(reshaped_array)

[[17.80415106  9.52765923  2.88787368 14.37015557 15.49952502]
 [16.94020624 16.58653919  8.64956199  5.22977406 15.07709748]
 [12.77279528  7.13744974 16.98808919  9.75738691 18.39519337]
 [12.05685587 12.41582629  9.17755999 13.847821   16.75668494]]


In [9]:
# Replace the max in each row by 0 (axis=1)
reshaped_array[np.arange(4), reshaped_array.argmax(axis=1)] = 0

print("Reshaped Array:\n", reshaped_array)


Reshaped Array:
 [[ 0.          9.52765923  2.88787368 14.37015557 15.49952502]
 [ 0.         16.58653919  8.64956199  5.22977406 15.07709748]
 [12.77279528  7.13744974 16.98808919  9.75738691  0.        ]
 [12.05685587 12.41582629  9.17755999 13.847821    0.        ]]


Video Link - https://drive.google.com/file/d/1XCVsqbnZ4eWisQhAle_aKahXPyTnQVyZ/view?usp=drive_link